name = "mheen"
compatibility_date = "2024-02-26"
pages_build_output_dir = ".vercel/output/static"

# ربط قاعدة البيانات
[[d1_databases]]
binding = "DB"
database_name = "mheen-archive-db"
database_id = "هنا_الرمز_الطويل"

# ربط مخزن الصور
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mheen-media"